const goodsData = {
	wordList: [
		{ ch: '回答', en: 'answer', id: 1001 },
		{ ch: '协会', en: 'association', id: 1002 },
		{ ch: '是', en: 'yew', id: 1003 },
		{ ch: '苹果', en: 'apple', id: 1004 },
		{ ch: '奶酪，干酪，茄子（照相说的）', en: 'cheese', id: 1005 },
		{ ch: '盒，箱', en: 'box', id: 1006 },
		{ ch: '买', en: 'buy', id: 1007 },
		{ ch: '加拿大的', en: 'Canadian', id: 1008 },
		{ ch: '汽车', en: 'car', id: 1009 },
		{ ch: '地毯', en: 'carpet', id: 1010 },
		{ ch: '携带，拿', en: 'carry', id: 1011 },
		{ ch: '便宜的', en: 'cheap', id: 1012 },
		{ ch: '城市', en: 'city', id: 1013 },
		{ ch: '外套', en: 'coat', id: 1014 },
		{ ch: '衣服', en: 'dress', id: 1015 },
		{ ch: '东方', en: 'wast', id: 1016 },
		{ ch: '八', en: 'eight', id: 1017 },
		{ ch: '英语', en: 'English', id: 1018 },
		{ ch: '足够', en: 'enough', id: 1019 },
		{ ch: '一切，任何事物', en: 'everything', id: 1020 },
		{ ch: '考试', en: 'exam', id: 1021 },
		{ ch: '借口，理由', en: 'excuse', id: 1022 },
		{ ch: '十五', en: 'fifteen', id: 1023 },
		{ ch: '结束', en: 'finish', id: 1024 },
		{ ch: '五', en: 'five', id: 1025 },
		{ ch: '四', en: 'four', id: 1026 },
		{ ch: '礼拜五', en: 'Friday', id: 1027 },
		{ ch: '起床', en: 'get up', id: 1028 },
		{ ch: '五', en: 'five', id: 1029 },
		{ ch: '理发，发型', en: 'haircut', id: 1030 },
		{ ch: '他自己', en: 'herself', id: 1031 },
		{ ch: '丘陵', en: 'hill', id: 1032 },
		{ ch: '假期', en: 'holiday', id: 1033 },
		{ ch: '房子', en: 'house', id: 1034 },
		{ ch: '这，它', en: 'it', id: 1035 },
		{ ch: '跳', en: 'jump', id: 1036 },
		{ ch: '只是，就', en: 'just', id: 1037 },
		{ ch: '离开', en: 'leave', id: 1038 },
		{ ch: '少，较少', en: 'less', id: 1039 },
		{ ch: '光，亮的', en: 'light', id: 1040 },
		{ ch: '听，倾听', en: 'listen', id: 1041 },
		{ ch: '看，寻找', en: 'look', id: 1042 },
		{ ch: '我', en: 'me', id: 1043 },
		{ ch: '中午', en: 'midday', id: 1044 },
		{ ch: '我自己', en: 'myself', id: 1045 },
		{ ch: '九', en: 'nine', id: 1046 },
		{ ch: '九十', en: 'ninety', id: 1047 },
		{ ch: '一个，一', en: 'one', id: 1048 },
		{ ch: '桔子，橙色', en: 'orange', id: 1049 },
		{ ch: '对，一对', en: 'pair', id: 1050 },
		{ ch: '原谅，赦免', en: 'pardon', id: 1051 },
		{ ch: '钢笔', en: 'pen', id: 1052 },
		{ ch: '铅笔', en: 'pencil', id: 1053 },
		{ ch: '分，便士', en: 'penny', id: 1054 },
		{ ch: '擦亮，磨光', en: 'polish', id: 1055 },
		{ ch: '目前的', en: 'present', id: 1056 },
		{ ch: '红色', en: 'red', id: 1057 },
		{ ch: '其他，其余', en: 'rest', id: 1058 },
		{ ch: '富有的', en: 'rich', id: 1059 },
		{ ch: '俄罗斯的', en: 'Russian', id: 1060 },
		{ ch: '看', en: 'see', id: 1061 },
		{ ch: '七', en: 'seven', id: 1062 },
		{ ch: '衬衫', en: 'shirt', id: 1063 },
		{ ch: '六', en: 'six', id: 1064 },
		{ ch: '裙子', en: 'skirt', id: 1065 },
		{ ch: '软的', en: 'soft', id: 1066 },
		{ ch: '酸的', en: 'sour', id: 1067 },
		{ ch: '站起来，起立', en: 'stand up', id: 1068 },
		{ ch: '欠考虑，笨的', en: 'stupid', id: 1069 },
		{ ch: '礼拜日', en: 'Sunday', id: 1070 },
		{ ch: '甜的', en: 'sweet', id: 1071 },
		{ ch: '桌子，表', en: 'table', id: 1072 },
		{ ch: '第三，三分之一', en: 'third', id: 1073 },
		{ ch: '这个', en: 'this', id: 1074 },
		{ ch: '三', en: 'three', id: 1075 },
		{ ch: '也，很，非常', en: 'too', id: 1076 },
		{ ch: '十二日', en: 'twelfth', id: 1077 },
		{ ch: '二', en: 'two', id: 1078 },
		{ ch: '雨伞', en: 'umbrella', id: 1079 },
		{ ch: '村庄', en: 'village', id: 1080 },
		{ ch: '旅游者，游客', en: 'visitor', id: 1081 },
		{ ch: '温暖', en: 'warm', id: 1082 },
		{ ch: '看，电视', en: 'watch', id: 1083 },
		{ ch: '原因，为什么', en: 'why', id: 1084 },
		{ ch: '你的', en: 'your', id: 1085 },
		{ ch: '年轻，青春，小伙子', en: 'youth', id: 1086 },
		{ ch: '面包', en: 'baker', id: 1087 },
		{ ch: '奇妙的，好奇的', en: 'curiously', id: 1088 },
		{ ch: '兴奋的，激动的', en: 'excited', id: 1089 },
		{ ch: '荷兰', en: 'Holland', id: 1090 },
		{ ch: '不锋利的', en: 'blunt', id: 1091 },
		{ ch: '不锋利的，坦言的', en: 'blunt', id: 1092 },
		{ ch: '书架', en: 'bookcase', id: 1093 },
		{ ch: '小手提包', en: 'handbag', id: 1094 },
		{ ch: '是', en: 'is', id: 1095 },
		{ ch: '谢谢你', en: 'thank you', id: 1096 },
		{ ch: '十分，非常', en: 'very much', id: 1097 },
		{ ch: '推销员', en: 'sales reps', id: 1098 },
		{ ch: '朝鲜，韩国', en: 'Korea', id: 1099 },
		{ ch: '腮腺炎', en: 'mumps', id: 1100 },
		{ ch: '公共汽车停靠站', en: 'bus stop', id: 1101 },
		{ ch: '昨晚，最后一夜', en: 'last night', id: 1102 },
		{ ch: '应声开门', en: 'answer the door', id: 1103 },
		{ ch: '在晚上', en: 'in the eveing', id: 1104 },
		{ ch: '我独立的', en: 'by myself', id: 1105 },
		{ ch: '我', en: 'I', id: 1106 },
		{ ch: '土耳其的', en: 'Turkish', id: 1107 },
		{ ch: '柏林', en: 'Berlin', id: 1108 },
		{ ch: '黑暗的', en: 'dark', id: 1109 },
		{ ch: '长的', en: 'long', id: 1110 },
		{ ch: '老的', en: 'old', id: 1111 },
		{ ch: '看一看', en: 'have a look', id: 1112 },
		{ ch: '非常讨厌的', en: 'terrible', id: 1113 },
		{ ch: '上床睡觉', en: 'go to bed', id: 1114 },
		{ ch: '在行走', en: 'on the march', id: 1115 },
		{ ch: '挪威', en: 'Norwegian', id: 1116 },
		{ ch: '终于', en: 'in the end', id: 1117 },
		{ ch: '很，相当', en: 'pretty', id: 1118 },
		{ ch: '十六分之一，第十六', en: 'sixteenty', id: 1119 },
		{ ch: '大于，超过', en: 'overtake', id: 1120 },
		{ ch: '波浪，波动', en: 'wave', id: 1121 },
		{ ch: '工程师，技师', en: 'engineer', id: 1122 },
		{ ch: '食品杂货店', en: 'grocer', id: 1123 },
		{ ch: '国籍', en: 'nationnality', id: 1124 },
		{ ch: '洗', en: 'wash', id: 1125 },
		{ ch: '烹饪', en: 'cook', id: 1126 },
		{ ch: '第十一', en: 'eleventh', id: 1127 },
		{ ch: '好几百', en: 'hundreds of', id: 1128 },
		{ ch: '亲子，我们自己', en: 'ourselves', id: 1129 },
		{ ch: '在...前面', en: 'in front of', id: 1130 },
		{ ch: '酒，瓶子', en: 'bottle', id: 1131 },
		{ ch: '或许，可能', en: 'perhaps', id: 1132 },
		{ ch: '也许，可能', en: 'thirteenth', id: 1133 },
		{ ch: '渴望，口渴', en: 'thirsty', id: 1134 },
		{ ch: '突然，忽然', en: 'suddenly', id: 1135 },
		{ ch: '晚，迟到', en: 'late', id: 1136 },
		{ ch: '切，割', en: 'cut', id: 1137 },
		{ ch: '小的，比较小的', en: 'little', id: 1138 },
		{ ch: '忙绿的', en: 'busy', id: 1139 },
		{ ch: '煮沸，烧开', en: 'boil', id: 1140 },
		{ ch: '教堂', en: 'church', id: 1141 },
		{ ch: '达到，出现', en: 'arrive', id: 1142 },
		{ ch: '告诉', en: 'tell', id: 1143 },
		{ ch: '你自己', en: 'yourself', id: 1144 },
		{ ch: '计算，数数', en: 'count', id: 1145 },
		{ ch: '懒惰的', en: 'lazy', id: 1146 }
	]
}

export default goodsData